"""v1.2-schema

Revision ID: 75cdda35b369
Revises: 
Create Date: 2026-03-11 00:53:56.538111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cdda35b369'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('test_path', sa.String(), nullable=True),
    sa.Column('auth_method', sa.String(), nullable=False),
    sa.Column('encrypted_token', sa.String(), nullable=True),
    sa.Column('encrypted_username', sa.String(), nullable=True),
    sa.Column('encrypted_password', sa.String(), nullable=True),
    sa.Column('api_key_name', sa.String(), nullable=True),
    sa.Column('encrypted_api_key', sa.String(), nullable=True),
    sa.Column('source_retry_limit', sa.Integer(), nullable=True),
    sa.Column('qualys_retry_limit', sa.Integer(), nullable=True),
    sa.Column('cron_schedule', sa.String(), nullable=True),
    sa.Column('schedule_enabled', sa.Integer(), nullable=False),
    sa.Column('execution_timeout', sa.Integer(), nullable=True),
    sa.Column('is_valid_mappings', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualys_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_url', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('connector_uuid', sa.String(), nullable=True),
    sa.Column('encrypted_password', sa.String(), nullable=True),
    sa.Column('encrypted_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('connector_endpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connector_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('pagination_config', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connector_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial_success', 'failed', 'skipped', name='runstatus'), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_submitted', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('error_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_history_connector_id'), 'run_history', ['connector_id'], unique=False)
    op.create_table('endpoint_run_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('endpoint_id', sa.String(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_submitted', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['connector_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['run_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_run_logs_endpoint_id'), 'endpoint_run_logs', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_endpoint_run_logs_run_id'), 'endpoint_run_logs', ['run_id'], unique=False)
    op.create_table('field_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('endpoint_id', sa.String(), nullable=False),
    sa.Column('target_field', sa.String(), nullable=False),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('source_field', sa.String(), nullable=True),
    sa.Column('static_value', sa.String(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('fallback', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['connector_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_failures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('record_identifier', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_failures_run_id'), 'run_failures', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_failures_run_id'), table_name='run_failures')
    op.drop_table('run_failures')
    op.drop_table('field_mappings')
    op.drop_index(op.f('ix_endpoint_run_logs_run_id'), table_name='endpoint_run_logs')
    op.drop_index(op.f('ix_endpoint_run_logs_endpoint_id'), table_name='endpoint_run_logs')
    op.drop_table('endpoint_run_logs')
    op.drop_index(op.f('ix_run_history_connector_id'), table_name='run_history')
    op.drop_table('run_history')
    op.drop_table('connector_endpoints')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('qualys_config')
    op.drop_table('connectors')
    # ### end Alembic commands ###
